name: Run Tests

on:
  push:
    branches:
      - main  # replace with 'master' if your default branch is named 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # or any other version you wish to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        cd unistrat
        python -m unittest discover -s test -p 'test_*.py'
